
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[382] =
    {   0,
        0,    0,  108,  106,  105,  104,   92,  106,   98,   91,
      106,   86,   87,   96,   95,   83,   94,   90,   97,   49,
       48,   84,   80,   99,   85,  100,  103,   46,   46,   88,
       89,  101,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   81,  102,
       82,   93,  104,   79,    0,   57,    0,   65,   82,   74,
       66,    0,    0,   63,   71,   61,   72,   62,   73,    0,
       52,   64,   53,   49,    0,    0,   49,   49,    0,   49,
       48,   48,   48,   48,   89,   81,   88,   70,   76,   78,
       77,   69,   46,    0,    0,   67,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,    8,   46,   46,   46,   46,   46,   46,   16,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   68,   75,   57,    0,    0,    0,    0,   50,    0,
        0,   58,    0,   52,    0,   53,    0,   51,   49,   49,
       49,   49,    0,   47,   48,   48,   48,   48,   60,   59,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   14,   46,   46,   18,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,    0,    0,    0,    0,    0,   52,    0,   53,   51,
       49,    0,    0,   47,    0,   47,   47,   48,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,    1,   46,
        3,    4,   46,   46,   46,   46,   10,   11,   46,   46,
       15,   46,   19,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   32,   46,   46,    0,    0,
        0,    0,    0,    0,   47,   47,    0,   54,   47,   47,
       46,   46,   38,   46,   46,   46,   46,   46,   46,   46,
        2,    5,   46,   46,   46,   46,   13,   46,   46,   46,
       46,   23,   46,   46,   46,   46,   46,   46,   30,   46,

       46,   34,    0,   55,    0,   56,   54,   47,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,    9,
       12,   17,   46,   46,   22,   24,   25,   26,   27,   28,
       46,   46,   46,   55,   56,   46,   46,   37,   46,   46,
       46,   46,   46,   46,   46,   46,    7,   46,   46,   29,
       46,   46,   35,   36,   39,   40,   46,   46,   46,   46,
       45,    6,   20,   21,   31,   33,   46,   42,   46,   46,
       41,   46,   46,   46,   46,   46,   46,   46,   44,   43,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   34,   36,   34,   37,   34,   38,
       34,   34,   39,   40,   41,   34,   34,   42,   34,   34,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   34,   57,   58,   59,   60,
       61,   62,   34,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    7,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    3,    1,    1,    8,    6,    6,    7,
        7,    7,    6,    8,    8,    8,    8,    8,    8,    9,
        8,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[391] =
    {   0,
        0,    0,  682,  683,  683,  678,  656,   71,   53,   72,
      635,  683,  683,  654,   68,  683,   69,   67,  653,  101,
       86,  651,  683,   89,  651,   64,  683,    0,   92,  683,
      683,  650,  121,  607,  609,   75,   29,   66,   41,  610,
       38,  609,  617,  107,  598,  106,  606,  611,  683,   84,
      683,  683,  662,  683,  102,  128,  111,  683,  683,  683,
      683,  101,  122,  683,  683,  683,  683,  683,  683,  649,
      164,  683,  187,  194,  236,  159,  149,  129,  648,  162,
      244,  161,  150,  183,  683,  683,  683,  638,  683,  683,
      683,  637,    0,  187,  616,  683,   76,  598,  597,  605,

      597,  594,  589,  598,  599,  586,  598,  585,  600,  587,
      593,  579,  580,  577,  577,  580,  577,  574,    0,  168,
      578,  134,  576,  139,  126,  580,  573,  629,   91,  176,
      577,  683,  683,  233,  627,  224,  253,    0,  683,  260,
        0,  683,  272,  683,  289,  683,  294,  298,  206,  683,
      595,  572,    0,  283,  207,  683,  593,  570,  683,  683,
      571,  565,  564,  565,  563,  574,  558,  572,  556,  552,
      556,  568,  563,  551,  201,  565,  563,  559,  551,  557,
      560,    0,  546,  550,    0,  551,  548,  538,  536,  538,
      540,  547,  533,  531,  531,  543,  533,  537,  531,  533,

      521,  276,  352,  314,  398,  308,  356,  318,  402,  683,
      683,  238,  267,  311,  347,  221,  282,  683,  521,  515,
      514,  498,  506,  495,  494,  480,  492,  483,    0,  484,
        0,    0,  475,  483,  472,  479,    0,    0,  473,  470,
        0,  474,    0,  469,  469,  468,  465,  477,  467,  471,
      476,  474,  471,  460,  465,    0,  452,  464,  239,    0,
      193,    0,  444,  453,  302,  683,  393,  457,  478,  455,
      452,  455,    0,  442,  436,  442,  431,  439,  446,  442,
        0,    0,  431,  432,  436,  427,    0,  434,  404,  412,
      406,    0,  408,  404,  404,  388,  397,  393,    0,  384,

      387,    0,  461,  465,  485,  489,  683,  683,  234,  391,
      388,  383,  377,  370,  385,  382,  385,  365,  359,    0,
        0,    0,  371,  358,    0,    0,    0,    0,    0,    0,
      354,  347,  340,  683,  683,  333,  342,    0,  325,  343,
      343,  327,  342,  340,  339,  333,    0,  315,  298,    0,
      311,  308,    0,    0,    0,    0,  292,  294,  305,  292,
        0,    0,    0,    0,    0,    0,  276,    0,  280,  281,
        0,  275,  283,  235,  202,  179,  163,   86,    0,    0,
      683,  547,  556,  560,  567,  574,  579,  581,  583,  585
    } ;

static const flex_int16_t yy_def[391] =
    {   0,
      381,    1,  381,  381,  381,  381,  381,  382,  381,  381,
      383,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  384,  384,  381,
      381,  381,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  381,  381,
      381,  381,  381,  381,  382,  381,  385,  381,  381,  381,
      381,  383,  386,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  387,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  384,  382,  383,  381,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  381,  381,  381,  381,  381,  382,  388,  381,  383,
      389,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  390,  387,  381,  381,  381,  381,  381,  381,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  382,  382,  383,  383,  381,  381,  381,  381,  381,
      381,  390,  390,  381,  381,  381,  381,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  382,  203,
      383,  205,  381,  381,  381,  381,  381,  381,  381,  381,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  381,  381,  381,  381,  381,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  381,  381,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
        0,  381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_nxt[759] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       29,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   28,   41,   28,   42,   28,   28,
       28,   28,   43,   44,   45,   46,   47,   48,   28,   28,
       28,   49,   50,   51,   52,   56,   58,   59,   60,   65,
      111,   70,   67,   71,   71,   71,   71,   91,   92,  112,
      119,   66,   68,   69,   86,   61,   94,  120,  116,   95,

       73,  117,   81,   81,   81,   81,   56,  132,  139,   87,
       94,   88,   89,   95,   57,   73,   76,   74,   74,   75,
       75,   82,  108,  113,  128,  114,   83,  137,  137,  109,
      134,   76,   94,  161,  115,  110,   77,   76,  140,  140,
      162,   78,   79,   84,   63,   57,  197,   97,   98,   99,
      380,   83,   76,  100,  198,  101,  133,  102,   80,  103,
      104,  123,  124,  135,  151,  129,   78,  105,  135,   79,
      147,  125,  147,  193,  126,  148,  148,  148,  148,  138,
       71,   71,   71,   71,  149,  157,  152,  187,  194,  150,
      141,   56,  191,  136,  143,  144,  155,  188,  189,  144,

      139,  156,  150,   71,   71,   71,   71,  158,   73,  192,
       74,   74,   75,   75,  150,  143,  144,  145,  146,  149,
      379,  144,  146,  156,   76,  184,  156,  150,   94,   77,
       57,  199,  185,  200,   78,  134,   63,   94,  145,  146,
      155,  378,  135,   56,  146,   76,  150,  156,  156,  377,
       73,   80,   75,   75,   75,   75,  269,   56,   73,   78,
       81,   81,   81,   81,  233,  234,   76,  139,  135,  202,
      202,  150,  156,  135,   76,  263,  204,  204,  270,   82,
       56,  336,   57,  206,   83,  206,  376,   76,  207,  207,
      207,  207,  259,  259,  337,   76,   57,  213,  136,  263,

      208,   84,  208,   63,  264,  209,  209,  209,  209,   83,
      148,  148,  148,  148,  148,  148,  148,  148,  214,   57,
      215,  139,  266,  216,  207,  207,  207,  207,  264,  210,
      261,  261,  375,  210,  209,  209,  209,  209,  374,  265,
      217,  373,  266,  372,  215,  371,  265,  266,  216,  370,
      210,  266,  369,  368,  367,  210,   56,   63,  267,  366,
      267,  365,  364,  268,  268,  268,  268,  266,  260,  260,
      260,  260,  207,  207,  207,  207,  266,  363,  260,  260,
      260,  260,  260,  260,  362,  361,  360,  144,  359,  358,
      357,  144,  356,  355,  354,   57,  353,  352,  351,  260,

      260,  260,  260,  260,  260,  139,  350,  349,  144,  268,
      268,  268,  268,  144,  262,  262,  262,  262,  209,  209,
      209,  209,  348,  347,  262,  262,  262,  262,  262,  262,
      346,  345,  344,  146,  343,  342,  341,  146,  340,  339,
      338,   63,  333,  332,  331,  262,  262,  262,  262,  262,
      262,  330,  329,  328,  146,  303,  327,  303,  326,  146,
      304,  304,  304,  304,  305,  325,  305,  324,  323,  306,
      306,  306,  306,  268,  268,  268,  268,  304,  304,  304,
      304,  304,  304,  304,  304,  322,  321,  320,  307,  319,
      318,  317,  307,  316,  315,  314,  334,  313,  312,  311,

      334,  306,  306,  306,  306,  306,  306,  306,  306,  307,
      310,  309,  308,  308,  307,  302,  301,  334,  300,  299,
      335,  298,  334,  297,  335,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  335,  280,  279,  278,  277,  335,   55,  276,   55,
       55,   55,   55,   55,   55,   55,   62,  275,   62,  274,
       62,   62,   62,   62,   62,   93,   93,   93,   93,   55,
       55,  273,   55,  272,  271,   55,   62,   62,  258,   62,
      257,  256,   62,  154,  154,  154,  203,  203,  205,  205,
      212,  212,  255,  254,  253,  252,  251,  250,  249,  248,

      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  218,  211,
      211,   94,  201,   94,  196,  195,  190,  186,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,   63,
      160,  159,  153,  142,   53,  131,  130,  127,  122,  121,
      118,  107,  106,   96,   90,   85,   72,   64,   63,   54,
       53,  381,    3,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[759] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,    9,   10,   15,
       37,   18,   17,   18,   18,   18,   18,   26,   26,   37,
       41,   15,   17,   17,   24,   10,   29,   41,   39,   29,

       21,   39,   21,   21,   21,   21,   55,   50,   62,   24,
       46,   24,   24,   46,    8,   20,   21,   20,   20,   20,
       20,   21,   36,   38,   46,   38,   21,   57,   57,   36,
       56,   20,   56,   97,   38,   36,   20,   21,   63,   63,
       97,   20,   20,   21,   62,   55,  129,   33,   33,   33,
      378,   21,   20,   33,  129,   33,   50,   33,   20,   33,
       33,   44,   44,   56,   78,   46,   20,   33,   56,   20,
       76,   44,   76,  125,   44,   76,   76,   76,   76,   57,
       71,   71,   71,   71,   77,   83,   78,  122,  125,   77,
       63,   94,  124,   56,   71,   71,   82,  122,  122,   71,

      261,   82,   80,   73,   73,   73,   73,   83,   74,  124,
       74,   74,   74,   74,   77,   71,   71,   73,   73,   80,
      377,   71,   73,   84,   74,  120,   82,   80,  136,   74,
       94,  130,  120,  130,   74,  134,  261,  134,   73,   73,
       84,  376,  136,  259,   73,   74,  149,  155,   84,  375,
       75,   74,   75,   75,   75,   75,  216,  137,   81,   74,
       81,   81,   81,   81,  175,  175,   75,  140,  134,  137,
      137,  149,  155,  134,   81,  212,  140,  140,  216,   81,
      202,  309,  259,  143,   81,  143,  374,   75,  143,  143,
      143,  143,  202,  202,  309,   81,  137,  154,  134,  212,

      145,   81,  145,  140,  213,  145,  145,  145,  145,   81,
      147,  147,  147,  147,  148,  148,  148,  148,  154,  202,
      154,  204,  217,  154,  206,  206,  206,  206,  213,  148,
      204,  204,  373,  148,  208,  208,  208,  208,  372,  217,
      154,  370,  265,  369,  154,  367,  214,  217,  154,  360,
      148,  214,  359,  358,  357,  148,  203,  204,  215,  352,
      215,  351,  349,  215,  215,  215,  215,  265,  203,  203,
      203,  203,  207,  207,  207,  207,  214,  348,  203,  203,
      203,  203,  203,  203,  346,  345,  344,  207,  343,  342,
      341,  207,  340,  339,  337,  203,  336,  333,  332,  203,

      203,  203,  203,  203,  203,  205,  331,  324,  207,  267,
      267,  267,  267,  207,  205,  205,  205,  205,  209,  209,
      209,  209,  323,  319,  205,  205,  205,  205,  205,  205,
      318,  317,  316,  209,  315,  314,  313,  209,  312,  311,
      310,  205,  301,  300,  298,  205,  205,  205,  205,  205,
      205,  297,  296,  295,  209,  263,  294,  263,  293,  209,
      263,  263,  263,  263,  264,  291,  264,  290,  289,  264,
      264,  264,  264,  268,  268,  268,  268,  303,  303,  303,
      303,  304,  304,  304,  304,  288,  286,  285,  268,  284,
      283,  280,  268,  279,  278,  277,  304,  276,  275,  274,

      304,  305,  305,  305,  305,  306,  306,  306,  306,  268,
      272,  271,  270,  269,  268,  258,  257,  304,  255,  254,
      306,  253,  304,  252,  306,  251,  250,  249,  248,  247,
      246,  245,  244,  242,  240,  239,  236,  235,  234,  233,
      230,  306,  228,  227,  226,  225,  306,  382,  224,  382,
      382,  382,  382,  382,  382,  382,  383,  223,  383,  222,
      383,  383,  383,  383,  383,  384,  384,  384,  384,  385,
      385,  221,  385,  220,  219,  385,  386,  386,  201,  386,
      200,  199,  386,  387,  387,  387,  388,  388,  389,  389,
      390,  390,  198,  197,  196,  195,  194,  193,  192,  191,

      190,  189,  188,  187,  186,  184,  183,  181,  180,  179,
      178,  177,  176,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  158,  157,  152,
      151,  135,  131,  128,  127,  126,  123,  121,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   95,
       92,   88,   79,   70,   53,   48,   47,   45,   43,   42,
       40,   35,   34,   32,   25,   22,   19,   14,   11,    7,
        6,    3,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[108] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 21 "scanner.l"
    // #include "globals.h"
    #include "parserNuevecito.tab.h"
    #define YY_USER_ACTION \
        yylloc.first_line = yylloc.last_line = yylineno; \
        yylloc.first_column = yylloc.last_column; \
        for(int i = 0; yytext[i] != '\0'; i++) { \
            if(yytext[i] == '\n') { \
                yylloc.last_line++; \
                yylloc.last_column = 0; \
            } \
            else { \
                yylloc.last_column++; \
            }\
        }
    #include <string.h>
    #include "globals.h"
    static int next_column = 1;
    int column = 1;
    char* line = NULL;
    int check_type(void);
    size_t line_alloc = 0;
    ssize_t line_sent, line_len = 0;

    // if (!available) { 
    //     free(line); 
    //     line = NULL; 
    //     line_alloc = line_sent = line_len = 0; 
    // } 

    #define YY_INPUT(buf, result, max_size) \
        ssize_t available = line_len - line_sent; \
        if (!available) { \
            line_sent = 0; \
            available = getline(&line, &line_alloc, yyin); \
            if (available < 0) { \
                available = 0; \
            } \
            line_len = available; \
        } \
        if (available > max_size) available = max_size; \
        memcpy(buf, line + line_sent, available); \
        line_sent += available; \
        if (!available) { \
            line_alloc = line_sent = line_len = 0; \
        } \
        result = available;
#line 811 "lex.yy.c"
#line 812 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 69 "scanner.l"

#line 1031 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 683 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 70 "scanner.l"
{ return(AUTO); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 71 "scanner.l"
{ return(BREAK); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "scanner.l"
{ return(CASE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 73 "scanner.l"
{ return(CHAR); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 74 "scanner.l"
{ return(CONST); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 75 "scanner.l"
{ return(CONTINUE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "scanner.l"
{ return(DEFAULT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "scanner.l"
{ return(DO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "scanner.l"
{ return(DOUBLE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "scanner.l"
{ return(ELSE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return(ENUM); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "scanner.l"
{ return(EXTERN); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "scanner.l"
{ return(FLOAT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "scanner.l"
{ return(FOR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "scanner.l"
{ return(GOTO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "scanner.l"
{ return(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return(INLINE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "scanner.l"
{ return(INT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "scanner.l"
{ return(LONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 89 "scanner.l"
{ return(REGISTER); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 90 "scanner.l"
{ return(RESTRICT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 91 "scanner.l"
{ return(RETURN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 92 "scanner.l"
{ return(SHORT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 93 "scanner.l"
{ return(SIGNED); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 94 "scanner.l"
{ return(SIZEOF); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 95 "scanner.l"
{ return(STATIC); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 96 "scanner.l"
{ return(STRUCT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 97 "scanner.l"
{ return(SWITCH); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "scanner.l"
{ return(TYPEDEF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 99 "scanner.l"
{ return(UNION); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "scanner.l"
{ return(UNSIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "scanner.l"
{ return(VOID); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "scanner.l"
{ return(VOLATILE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "scanner.l"
{ return(WHILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "scanner.l"
{ return _ALIGNAS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "scanner.l"
{ return _ALIGNOF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "scanner.l"
{ return _ATOMIC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "scanner.l"
{ return _BOOL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 108 "scanner.l"
{ return _COMPLEX; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 109 "scanner.l"
{ return _GENERIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return _IMAGINARY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "scanner.l"
{ return _NORETURN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "scanner.l"
{ return _STATIC_ASSERT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "scanner.l"
{ return _THREAD_LOCAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "scanner.l"
{ return FUNC_NAME; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return check_type(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "scanner.l"
{ return INTEGER_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "scanner.l"
{ return INTEGER_CONSTANT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "scanner.l"
{ return INTEGER_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 121 "scanner.l"
{ return INTEGER_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "scanner.l"
{ return FLOATING_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "scanner.l"
{ return FLOATING_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "scanner.l"
{ return FLOATING_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "scanner.l"
{ return FLOATING_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "scanner.l"
{ return FLOATING_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "scanner.l"
{ return FLOATING_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 130 "scanner.l"
{ return STRING_LITERAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "scanner.l"
{ return ELLIPSIS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "scanner.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "scanner.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "scanner.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "scanner.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "scanner.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "scanner.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "scanner.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "scanner.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "scanner.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "scanner.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 143 "scanner.l"
{ return RIGHT_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 144 "scanner.l"
{ return LEFT_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "scanner.l"
{ return INC_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "scanner.l"
{ return DEC_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 147 "scanner.l"
{ return PTR_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 148 "scanner.l"
{ return AND_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 149 "scanner.l"
{ return OR_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return LE_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "scanner.l"
{ return GE_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 152 "scanner.l"
{ return EQ_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "scanner.l"
{ return NE_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "scanner.l"
{ return ';'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "scanner.l"
{ return '{'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 156 "scanner.l"
{ return '}'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 157 "scanner.l"
{ return ','; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "scanner.l"
{ return ':'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 159 "scanner.l"
{ return '='; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 160 "scanner.l"
{ return '('; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 161 "scanner.l"
{ return ')'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 162 "scanner.l"
{ return '['; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 163 "scanner.l"
{ return ']'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 164 "scanner.l"
{ return '.'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 165 "scanner.l"
{ return '&'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 166 "scanner.l"
{ return '!'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 167 "scanner.l"
{ return '~'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 168 "scanner.l"
{ return '-'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 169 "scanner.l"
{ return '+'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 170 "scanner.l"
{ return '*'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 171 "scanner.l"
{ return '/'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 172 "scanner.l"
{ return '%'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 173 "scanner.l"
{ return '<'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 174 "scanner.l"
{ return '>'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 175 "scanner.l"
{ return '^'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 176 "scanner.l"
{ return '|'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 177 "scanner.l"
{ return '?'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 179 "scanner.l"
{ }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 180 "scanner.l"
{ next_column = 1; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 181 "scanner.l"
{ }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 183 "scanner.l"
ECHO;
	YY_BREAK
#line 1634 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 183 "scanner.l"


int yywrap(void) {
    return 1;         
}

int get_symbol_idx (char* value) {
    for (int i = 0 ; i < symbolTable.nullsym; i++){
        if (strcmp(symbolTable.symbols[i].lexeme, value) == 0)
            return i;
    }
    return -1;
}

int get_symbol_type(char* value) {
    for(int i = 0 ; i < symbolTable.nullsym; i++) {
        if (strcmp(symbolTable.symbols[i].lexeme, value) == 0)
            return symbolTable.symbols[i].type;
    }
    return -1;
}

void add_symbol_to_symbolTable(Symbol symbol) {
    if (symbolTable.nullsym >= symbolTable.size ) {
        symbolTable.size *= 2;
        Symbol* new_symbolTable = realloc(symbolTable.symbols, symbolTable.size * sizeof(Symbol));
        if (new_symbolTable == NULL) {
            printf("Unable to allocate enough memory for symbol table");
            exit(-1);
        } else {
            symbolTable.symbols = new_symbolTable;
        }
    }   
    int symbol_idx = get_symbol_idx(symbol.lexeme);
    if (symbol_idx == -1) {
        symbolTable.symbols[symbolTable.nullsym++] = symbol;
    } else {
        symbolTable.symbols[symbol_idx] = symbol;
    }
}

void show_symbol_table() {
    printf("\n********** Symbol Table **********\n");
    printf("Length: %d \n", symbolTable.nullsym);
    for (int i = 0; i < symbolTable.nullsym; i++) {
        printf("\t%s -> %d\n", symbolTable.symbols[i].lexeme, symbolTable.symbols[i].type);

        // if (strchr(symbolTable.pp_ids[i].lexeme, '"') != 0) {
        //     printf("%s -> %s\n", symbolTable.pp_ids[i].name, symbolTable.pp_ids[i].lexeme);
        // }
    }
    printf("Length: %d. Max size: %d \n", symbolTable.nullsym, symbolTable.size);
    printf("********************\n\n");
}


int check_type(void) {
    //printf("CHECK_TYPE: %d\n", typedef_name_flag);
    Symbol new_symbol;
    if (typedef_name_flag == 1) {
        new_symbol.type = TYPEDEF_NAME;
        new_symbol.lexeme = malloc(sizeof(char) * (strlen(yytext) + 1));
        strcpy(new_symbol.lexeme, yytext);
        add_symbol_to_symbolTable(new_symbol);
        typedef_name_flag = 0;
        // show_symbol_table();
        return TYPEDEF_NAME;
    } 
    else if (typedef_name_flag == 2) {
        typedef_name_flag = 0;
        if (get_symbol_type(yytext) != -1) {
            return TYPEDEF_NAME; 
        } else {
            return IDENTIFIER;
        }
    }
    else {
        return IDENTIFIER;
    }
    return IDENTIFIER;
}
